import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from openpyxl import Workbook


def create_test_excel(file_path="report.xlsx"):
    """Create a simple Excel file with dummy data."""
    wb = Workbook()
    sheet = wb.active
    sheet.title = "Test Report"

    # Header row
    sheet.append(["ID", "Name", "Email"])

    # Dummy data rows
    test_data = [
        [1, "Krishna", "krishna@example.com"],
        [2, "Isha", "isha@example.com"],
        [3, "Harshada", "harshada@example.com"],
    ]

    for row in test_data:
        sheet.append(row)

    wb.save(file_path)
    return file_path


def send_email_with_attachment(
    smtp_host,
    smtp_port,
    smtp_user,
    smtp_pass,
    to_email,
    subject,
    body,
    attachment_path
):
    """Send email with an Excel attachment."""
    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = to_email
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    # Attachment
    part = MIMEBase("application", "octet-stream")
    with open(attachment_path, "rb") as f:
        part.set_payload(f.read())
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f"attachment; filename={attachment_path}")

    msg.attach(part)

    # SMTP connection
    server = smtplib.SMTP(smtp_host, smtp_port)
    server.starttls()
    server.login(smtp_user, smtp_pass)
    server.send_message(msg)
    server.quit()

    print("Email sent successfully!")


if __name__ == "__main__":
    print("Running test script...")

    # Reading environment variables from GitHub Secrets
    SMTP_HOST = os.getenv("SMTP_HOST")
    SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
    SMTP_USER = os.getenv("SMTP_USER")
    SMTP_PASS = os.getenv("SMTP_PASS")
    TO_EMAIL = os.getenv("TO_EMAIL")

    # Step 1: Create test Excel
    print("Creating test Excel file...")
    excel_file = create_test_excel()

    # Step 2: Send email
    print("Sending email...")
    send_email_with_attachment(
        smtp_host=SMTP_HOST,
        smtp_port=SMTP_PORT,
        smtp_user=SMTP_USER,
        smtp_pass=SMTP_PASS,
        to_email=TO_EMAIL,
        subject="Test Report - GitHub Actions",
        body="Hello,\n\nThis is a test report generated by GitHub Actions.\nEverything is working.\n\n– Automation Bot",
        attachment_path=excel_file
    )

    print("Test workflow complete!")
